### ISSUE TITLE
Backups not working in case var & media folders are symlinks

### ISSUE THREAD

**Issue by frenck** [bragento/bragento-composer-installer#23]
We use a setup where media & var folders are symlinked into Magento. We need to use multiple frontends and in our case the media & var folders are stored on a shared file system between the several frontends.

Currently the installer seems to be skipping symlinked files in it's backup:

https://github.com/bragento/bragento-composer-installer/blob/master/src/Updater/Core.php#L189

Can this be fixed?

**Comment by davidverholen** [comment]
Hey @frenck,

a Backup for the symlinked Folders would not be necessary since they are already stored outside of the Magento Installation.

I think a good Solution might be, to just save the symlink target paths and restore them after the core update. Would this solve your Problem?

**Comment by frenck** [comment]
That might solve it, but that is not the point.

The installer creates a backup of files & folders and restores it afterwards. I'm reporting that this is failing in case there are symlinks involved anywhere in the backup targets.

Assuming that the purpose of a backup is to restore it exactly in it's old state?

**Comment by davidverholen** [comment]
exactly, it shoud restore specific folders and files since the core update overwrites them. So for symlinks it should then (after the update) remove the folders and recreate the symlinks
