### ISSUE TITLE
Magento EE 1.14.2.2 -> Failed to copy pkginfo

### ISSUE THREAD

**Issue by frenck** [bragento/bragento-composer-installer#24]
Tried to upgrade to Magento EE 1.14.2.2 (for which I run a private repo of course). Seems like the pkginfo folder is removed from the new release.

This causes the installer to fail:

Generating autoload files
post update:
Deployment of magento-core magento-ee/core (v1.14.2.2) [update] <copy>
backup persistent files
var
media
app/etc/local.xml
starting core deployment
Failed to copy "vendor/magento-ee/core/pkginfo" because file does not exist.

**Comment by davidverholen** [comment]
Hello @frenck ,

the installer only copies the files that are defined in the mapping of your repository (modman, composer map or package.xml)

You have to remove the file in your mapping

**Comment by frenck** [comment]
Aah ok, found it it's the mapping in my composer.json :S

**Comment by frenck** [comment]
Lol, just missed your comment... thx

**Comment by davidverholen** [comment]
hehe ok,

I didn't even test it with EE. nice to know that it works
